spring:
  application:
    name: HSBC-INCIDENT-MANAGEMENT
  datasource:
    url: jdbc:h2:mem:incident
    driverClassName: org.h2.Driver
    username: sa
    password: password
    schema: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080